-- FILE OR LOADING ALL DATA & INSERTS

-- load into mega table
LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2018.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

-- load information data from only most recent 2018
INSERT INTO basic_info
SELECT DISTINCT UNITID, INSTNM
FROM education_mega;


-- load 2018 data into rest of normalized tables
INSERT INTO school_profile
SELECT UNITID, CONTROL, NPCURL, INSTURL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info);

INSERT INTO years 
VALUE('2018');

INSERT INTO admission
SELECT UNITID, '2018', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO geographical_data
SELECT UNITID, CITY, STABBR, ZIP
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2018', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2018', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2018', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2018', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2016 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2016.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2016');

INSERT INTO admission
SELECT UNITID, '2016', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2016', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2016', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2016', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2016', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2015 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2015.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2015');

INSERT INTO admission
SELECT UNITID, '2015', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2015', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2015', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2015', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2015', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2016 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2016.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2016');

INSERT INTO admission
SELECT UNITID, '2016', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2016', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2016', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2016', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2016', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2014 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2014.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2014');

INSERT INTO admission
SELECT UNITID, '2014', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2014', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2014', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2014', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2014', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2013 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2013.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2013');

INSERT INTO admission
SELECT UNITID, '2013', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2013', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2013', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2013', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2013', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2012 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2012.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2012');

INSERT INTO admission
SELECT UNITID, '2012', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2012', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2012', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2012', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2012', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2011 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2011.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2011');

INSERT INTO admission
SELECT UNITID, '2011', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2011', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2011', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2011', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2011', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2010 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2010.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2010');

INSERT INTO admission
SELECT UNITID, '2010', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2010', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2010', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2010', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2010', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2009 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2009.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2009');

INSERT INTO admission
SELECT UNITID, '2009', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2009', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2009', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2009', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2009', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2008.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2008');

INSERT INTO admission
SELECT UNITID, '2008', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2008', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2008', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2008', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2008', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2007 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2007.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2007');

INSERT INTO admission
SELECT UNITID, '2007', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2007', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2007', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2007', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2007', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2006 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2006.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2006');

INSERT INTO admission
SELECT UNITID, '2006', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2006', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2006', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2006', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2006', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2005 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2005.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2005');

INSERT INTO admission
SELECT UNITID, '2005', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2005', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2005', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2005', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2005', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2004 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2004.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2004');

INSERT INTO admission
SELECT UNITID, '2004', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2004', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2004', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2004', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2004', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2003 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2003.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2003');

INSERT INTO admission
SELECT UNITID, '2003', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2003', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2003', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2003', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2003', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2002 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2002.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2002');

INSERT INTO admission
SELECT UNITID, '2002', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2002', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2002', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2002', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2002', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2001 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2001.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2001');

INSERT INTO admission
SELECT UNITID, '2001', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2001', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2001', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2001', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2001', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 2000 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N2000.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('2000');

INSERT INTO admission
SELECT UNITID, '2000', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '2000', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '2000', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '2000', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '2000', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 1999 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N1999.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('1999');

INSERT INTO admission
SELECT UNITID, '1999', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '1999', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '1999', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '1999', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '1999', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 1998 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N1998.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('1998');

INSERT INTO admission
SELECT UNITID, '1998', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '1998', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '1998', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '1998', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '1998', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 1997 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N1997.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('1997');

INSERT INTO admission
SELECT UNITID, '1997', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '1997', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '1997', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '1997', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '1997', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

-- insert 1996 table data;
DELETE FROM education_mega;

LOAD DATA LOCAL INFILE '~/Downloads/CollegeScorecard_Raw_Data/N1996.csv' 
INTO TABLE education_mega FIELDS TERMINATED BY ',' ENCLOSED BY "" 
LINES TERMINATED BY '\n';

DELETE FROM education_mega
WHERE UNITID = 0;

INSERT INTO years 
VALUE('1996');

INSERT INTO admission
SELECT UNITID, '1996', ADM_RATE, ADM_RATE_ALL
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO demographic_data
SELECT UNITID, '1996', UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISPANIC,
UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR,UGDS_NRA, UGDS_UNKNOWN, UGDS_MEN,
UGDS_WOMEN, PAR_ED_PCT_1STGEN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO act_stat
SELECT UNITID, '1996', ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25,
ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO sat_stats
SELECT UNITID, '1996', SAT_AVG,SAT_AVG_ALL, SATVR25, SATVR75, SATMT25,
SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

INSERT INTO cost_earnings
SELECT UNITID, '1996', COSTT4_A, TUITIONFEE_IN, TUITIONFEE_OUT,
PCTFLOAN, PCTPELL, DEBT_MDN
FROM education_mega
WHERE UNITID IN (
SELECT UNITID
FROM basic_info); 

