CREATE DATABASE IF NOT EXISTS project2;

DROP TABLE IF EXISTS education_mega;

CREATE TABLE education_mega(
UNITID MEDIUMINT UNSIGNED,
INSTNM TEXT NOT NULL,
CITY TEXT,
STABBR VARCHAR(2),
ZIP VARCHAR(9),
-- url of website
INSTURL TEXT,
-- url of net price calculator
NPCURL TEXT,
SCH_DEG TINYINT UNSIGNED,
-- serious financial/compliance issues
HCM2 BOOL,
-- predominant undergrad degree
PREDDEG TINYINT UNSIGNED,
-- highest award possible conferred
HIGHDEG TINYINT UNSIGNED,
--  public, private nonprofit, or private for-profit. btw 1-3!!! trigger
CONTROL TINYINT UNSIGNED,
ADM_RATE DECIMAL(6,5) UNSIGNED,
ADM_RATE_ALL DECIMAL(6,5) UNSIGNED,
SATVR25 SMALLINT UNSIGNED,
SATVR75 SMALLINT UNSIGNED,
SATMT25 SMALLINT UNSIGNED,
SATMT75 SMALLINT UNSIGNED,
SATWR25 SMALLINT UNSIGNED,
SATWR75 SMALLINT UNSIGNED,
SATVRMID SMALLINT UNSIGNED,
SATMTMID SMALLINT UNSIGNED,
SATWRMID SMALLINT UNSIGNED,
ACTCM25 TINYINT UNSIGNED,
ACTCM75 TINYINT UNSIGNED,
ACTEN25 TINYINT UNSIGNED,
ACTEN75 TINYINT UNSIGNED,
ACTMT25 TINYINT UNSIGNED,
ACTMT75 TINYINT UNSIGNED,
ACTWR25 TINYINT UNSIGNED,
ACTWR75 TINYINT UNSIGNED,
ACTCMMID TINYINT UNSIGNED,
ACTENMID TINYINT UNSIGNED,
ACTMTMID TINYINT UNSIGNED,
ACTWRMID TINYINT UNSIGNED,
SAT_AVG SMALLINT UNSIGNED,
SAT_AVG_ALL SMALLINT UNSIGNED,
UGDS INT UNSIGNED,
UGDS_WHITE INT UNSIGNED,
UGDS_NRA INT UNSIGNED,
UGDS_UNKNOWN INT UNSIGNED,
UGDS_BLACK INT UNSIGNED,
UGDS_API INT UNSIGNED,
UGDS_HISPANIC INT UNSIGNED,
COSTT4_A SMALLINT UNSIGNED,
TUITIONFEE_IN SMALLINT UNSIGNED,
TUITIONFEE_OUT SMALLINT UNSIGNED,
PCTFLOAN FLOAT UNSIGNED,
PCTPELL FLOAT UNSIGNED,
DEBT_MDN INT UNSIGNED,
PAR_ED_PCT_1STGEN FLOAT UNSIGNED
);

DROP TABLE IF EXISTS basic_info;
CREATE TABLE basic_info(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTNM TEXT NOT NULL,
PRIMARY KEY basic_pk (UNITID, INSTNM)
);

DROP TABLE IF EXISTS school_profile;
CREATE TABLE school_profile(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTNM TEXT NOT NULL,
SCH_DEG TINYINT UNSIGNED,
HCM2 BOOL,
PREDDEG TINYINT UNSIGNED,
HIGHDEG TINYINT UNSIGNED,
CONTROL TINYINT UNSIGNED,
NSTURL TEXT,
INPCURL TEXT,
ADM_RATE DECIMAL(6,5) UNSIGNED,
ADM_RATE_ALL DECIMAL(6,5) UNSIGNED,
PRIMARY KEY geo_pk (UNITID, INSTM),
FOREIGN KEY geo_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);

DROP TABLE IF EXISTS geographical_data;
CREATE TABLE geographical_data(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTM TEXT NOT NULL,
CITY TEXT,
STABBR VARCHAR(2),
ZIP VARCHAR(9),
PRIMARY KEY geo_pk (UNITID, INSTM),
FOREIGN KEY geo_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);

DROP TABLE IF EXISTS demographic_data;
CREATE TABLE demographic_data(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTM TEXT NOT NULL,
UGDS INT UNSIGNED,
UGDS_WHITE INT UNSIGNED,
UGDS_NRA INT UNSIGNED,
UGDS_UNKNOWN INT UNSIGNED,
UGDS_BLACK INT UNSIGNED,
UGDS_API INT UNSIGNED,
UGDS_HISPANIC INT UNSIGNED,
PAR_ED_PCT_1STGEN FLOAT UNSIGNED,
PRIMARY KEY demo_pk (UNITID, INSTM),
FOREIGN KEY demo_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);

DROP TABLE IF EXISTS act_stat;
CREATE TABLE act_stat(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTM TEXT NOT NULL,
ACTCM25 TINYINT UNSIGNED,
ACTCM75 TINYINT UNSIGNED,
ACTEN25 TINYINT UNSIGNED,
ACTEN75 TINYINT UNSIGNED,
ACTMT25 TINYINT UNSIGNED,
ACTMT75 TINYINT UNSIGNED,
ACTWR25 TINYINT UNSIGNED,
ACTWR75 TINYINT UNSIGNED,
ACTCMMID TINYINT UNSIGNED,
ACTENMID TINYINT UNSIGNED,
ACTMTMID TINYINT UNSIGNED,
ACTWRMID TINYINT UNSIGNED,
PRIMARY KEY act_pk (UNITID, INSTM),
FOREIGN KEY act_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);

DROP TABLE IF EXISTS sat_stats;
CREATE TABLE sat_stats(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTM TEXT NOT NULL,
SAT_AVG SMALLINT UNSIGNED,
SAT_AVG_ALL SMALLINT UNSIGNED,
SATVR25 SMALLINT UNSIGNED,
SATVR75 SMALLINT UNSIGNED,
SATMT25 SMALLINT UNSIGNED,
SATMT75 SMALLINT UNSIGNED,
SATWR25 SMALLINT UNSIGNED,
SATWR75 SMALLINT UNSIGNED,
SATVRMID SMALLINT UNSIGNED,
SATMTMID SMALLINT UNSIGNED,
SATWRMID SMALLINT UNSIGNED,
PRIMARY KEY act_pk (UNITID, INSTM),
FOREIGN KEY act_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);

DROP TABLE IF EXISTS cost_earnings;
CREATE TABLE cost_earnings(
UNITID MEDIUMINT UNSIGNED NOT NULL,
INSTM TEXT NOT NULL,
COSTT4_A SMALLINT UNSIGNED,
TUITIONFEE_IN SMALLINT UNSIGNED,
TUITIONFEE_OUT SMALLINT UNSIGNED,
PCTFLOAN FLOAT UNSIGNED,
PCTPELL FLOAT UNSIGNED,
DEBT_MDN INT UNSIGNED,
PRIMARY KEY act_pk (UNITID, INSTM),
FOREIGN KEY act_fk (UNITID, INSTM) 
REFERENCES basic_info(UNITID, INSTM)
);
